# View GraphRAG Entities and Relationships
This notebook loads GraphRAG artifacts and displays entities and relationships as pandas DataFrames.

In [5]:
import pandas as pd
from pathlib import Path
import json 
artifacts_dir = Path('/home/karimnazarovj/RABBIT_mysql/knowledge/mysql/graph/output/artifacts')

entities_df = pd.read_parquet(artifacts_dir / 'create_final_entities.parquet')
relationships_df = pd.read_parquet(artifacts_dir / 'create_final_relationships.parquet')

# pandas display don't cut text in cells, so we can see full descriptions
# pd.set_option('display.max_colwidth', None)

# load up all the names of knobs from knowledge/postgres/system_view_origin.json. It's a dictionary, so you can get the keys
with open('/home/karimnazarovj/Rabbit/knowledge/mysql/system_view.json', 'r') as f:
    system_view_origin = json.load(f)
    all_knobs = list(system_view_origin.keys())

In [6]:
print('Entities shape:', entities_df.shape)
print('Relationships shape:', relationships_df.shape)

Entities shape: (80, 7)
Relationships shape: (51, 10)

In [7]:
entities_df[['name', 'type', 'description' ]].head(20)

,name,type,description
0,MYSQL,ORGANIZATION,MySQL is an open-source relational database ma...
1,MEMORY STORAGE ENGINE,ORGANIZATION,The MEMORY storage engine is used in MySQL for...
2,TEMPTABLE STORAGE ENGINE,ORGANIZATION,The TempTable storage engine is a component of...
3,INNODB,ORGANIZATION,InnoDB is a storage engine for MySQL renowned ...
4,TMP_TABLE_SIZE,EVENT,Defines the maximum size of internal in-memory...
5,MAX_HEAP_TABLE_SIZE,EVENT,Sets the maximum size to which user-created ME...
6,QUERY_PREALLOC_SIZE,EVENT,A deprecated MySQL variable as of version 8.0....
7,SORT_BUFFER_SIZE,EVENT,Defines the buffer size allocated for sorting ...
8,INNODB_BUFFER_POOL_SIZE,EVENT,Specifies the size of the buffer pool in InnoD...
9,INNODB_MAX_DIRTY_PAGES_PCT_LWM,EVENT,Defines a low water mark for dirty pages in In...
10,INNODB_PURGE_THREADS,EVENT,Specifies the number of background threads for...
11,TABLE_OPEN_CACHE_INSTANCES,EVENT,Defines the number of open tables cache instan...
12,INNODB_COMPRESSION_FAILURE_THRESHOLD_PCT,EVENT,Defines the compression failure rate threshold...
13,INNODB_CHANGE_BUFFERING,EVENT,Specifies whether InnoDB performs change buffe...
14,INNODB_ONLINE_ALTER_LOG_MAX_SIZE,EVENT,Specifies the upper limit on the size of tempo...
15,MYSQL 8.0.29,EVENT,A version of MySQL where the query_prealloc_si...
16,MYSQL 8.0.28,,
17,DDL OPERATION,EVENT,DDL (Data Definition Language) operations invo...
18,DML OPERATION,EVENT,DML (Data Manipulation Language) operations in...
19,ALTER TABLE OPERATION,EVENT,An ALTER TABLE operation is a specific type of...

In [8]:
## Count how many entities in the graph are not knobs
all_knobs_lower = {k.lower() for k in all_knobs}

# get a list of all entitity names from dataframe
entity_names = entities_df['name'].tolist()
non_knob_entities = []
for entity_name in entity_names:
    # convert to lowercase and if more than one word, add '_' between words, then check if it's in all_knobs_lower
    entity_name_processed = entity_name.lower()
    if entity_name_processed not in all_knobs_lower:
        non_knob_entities.append(entity_name)


print('Total entities:', len(entity_names))
print('Non-knobs:', len(non_knob_entities))

Total entities: 80
Non-knobs: 22

In [9]:
# print some examples of non-knob entities 
entities_df[['name', 'type', 'description']].head(10)

,name,type,description
0,MYSQL,ORGANIZATION,MySQL is an open-source relational database ma...
1,MEMORY STORAGE ENGINE,ORGANIZATION,The MEMORY storage engine is used in MySQL for...
2,TEMPTABLE STORAGE ENGINE,ORGANIZATION,The TempTable storage engine is a component of...
3,INNODB,ORGANIZATION,InnoDB is a storage engine for MySQL renowned ...
4,TMP_TABLE_SIZE,EVENT,Defines the maximum size of internal in-memory...
5,MAX_HEAP_TABLE_SIZE,EVENT,Sets the maximum size to which user-created ME...
6,QUERY_PREALLOC_SIZE,EVENT,A deprecated MySQL variable as of version 8.0....
7,SORT_BUFFER_SIZE,EVENT,Defines the buffer size allocated for sorting ...
8,INNODB_BUFFER_POOL_SIZE,EVENT,Specifies the size of the buffer pool in InnoD...
9,INNODB_MAX_DIRTY_PAGES_PCT_LWM,EVENT,Defines a low water mark for dirty pages in In...

In [10]:
# show all non-knob entities
entities_df[entities_df['name'].isin(non_knob_entities)][['name', 'type', 'description']]

,name,type,description
0,MYSQL,ORGANIZATION,MySQL is an open-source relational database ma...
1,MEMORY STORAGE ENGINE,ORGANIZATION,The MEMORY storage engine is used in MySQL for...
2,TEMPTABLE STORAGE ENGINE,ORGANIZATION,The TempTable storage engine is a component of...
3,INNODB,ORGANIZATION,InnoDB is a storage engine for MySQL renowned ...
15,MYSQL 8.0.29,EVENT,A version of MySQL where the query_prealloc_si...
16,MYSQL 8.0.28,,
17,DDL OPERATION,EVENT,DDL (Data Definition Language) operations invo...
18,DML OPERATION,EVENT,DML (Data Manipulation Language) operations in...
19,ALTER TABLE OPERATION,EVENT,An ALTER TABLE operation is a specific type of...
39,MYSQL SERVER,ORGANIZATION,MySQL Server is a widely used open-source rela...
40,PERFORMANCE SCHEMA,ORGANIZATION,Performance Schema is a feature in MySQL that ...
41,MYISAM,ORGANIZATION,MyISAM is a storage engine for MySQL that is o...
42,FULLTEXT SEARCH INDEX,EVENT,Full-text search index is a feature in MySQL t...
53,HOST CACHE,,
54,FULLTEXT INDEX,EVENT,A FullText Index is a special type of index in...
55,BINARY LOG,EVENT,The Binary Log is a set of log files that cont...
56,UNDO TABLESPACE,EVENT,Undo Tablespace is a storage area in MySQL whe...
57,THREADS,EVENT,Threads in MySQL are used for parallel process...
58,TRANSACTION,EVENT,A Transaction in MySQL is a sequence of operat...
59,ALLOCATION BLOCK SIZE,,
78,STORED PROGRAM DEFINITION CACHE,ORGANIZATION,The stored program definition cache manages th...
79,TABLESPACE DEFINITION CACHE,ORGANIZATION,The tablespace definition cache sets a limit f...

In [11]:
relationships_df[['source', 'target', 'weight', 'description']].head()

,source,target,weight,description
0,MYSQL,MEMORY STORAGE ENGINE,8.0,The MEMORY storage engine is used in MySQL for...
1,MYSQL,TEMPTABLE STORAGE ENGINE,8.0,The TempTable storage engine is used in MySQL ...
2,MYSQL,INNODB,10.0,InnoDB is a storage engine used within MySQL t...
3,MEMORY STORAGE ENGINE,TMP_TABLE_SIZE,7.0,TMP_TABLE_SIZE defines the maximum size of int...
4,MEMORY STORAGE ENGINE,MAX_HEAP_TABLE_SIZE,7.0,MAX_HEAP_TABLE_SIZE sets the maximum size to w...

In [12]:
# print how many total relationships
print('Total relationships:', relationships_df.shape[0])
# print how many relationships where source and target are both knobs
knob_relationships = relationships_df[
    relationships_df['source'].str.lower().isin(all_knobs_lower) &
    relationships_df['target'].str.lower().isin(all_knobs_lower)
]
print('Knob relationships:', knob_relationships.shape[0])

Total relationships: 51
Knob relationships: 2

In [13]:
# print some examples of knob relationships
knob_relationships[['source', 'target', 'weight', 'description']].head()

# print the entire description text
pd.set_option('display.max_colwidth', None)
knob_relationships[['source', 'target', 'weight', 'description']].head()

,source,target,weight,description
49,BINLOG_GROUP_COMMIT_SYNC_DELAY,BINLOG_GROUP_COMMIT_SYNC_NO_DELAY_COUNT,7.0,BINLOG_GROUP_COMMIT_SYNC_NO_DELAY_COUNT is dependent on the delay set by BINLOG_GROUP_COMMIT_SYNC_DELAY
50,INNODB_LOG_SPIN_CPU_ABS_LWM,INNODB_LOG_SPIN_CPU_PCT_HWM,1.0,Both variables define CPU usage thresholds for user threads spinning while waiting for flushed redo

In [14]:
# print some examples of relationships
relationships_df[['source', 'target', 'weight', 'description']]

,source,target,weight,description
0,MYSQL,MEMORY STORAGE ENGINE,8.0,The MEMORY storage engine is used in MySQL for creating internal in-memory temporary tables
1,MYSQL,TEMPTABLE STORAGE ENGINE,8.0,The TempTable storage engine is used in MySQL for creating internal in-memory temporary tables as of MySQL 8.0.28
2,MYSQL,INNODB,10.0,"InnoDB is a storage engine used within MySQL to manage database operations. It provides transaction-safe tables, ensuring that database transactions are processed reliably and securely."
3,MEMORY STORAGE ENGINE,TMP_TABLE_SIZE,7.0,TMP_TABLE_SIZE defines the maximum size of internal in-memory temporary tables created by the MEMORY storage engine
4,MEMORY STORAGE ENGINE,MAX_HEAP_TABLE_SIZE,7.0,MAX_HEAP_TABLE_SIZE sets the maximum size to which user-created MEMORY tables are permitted to grow
5,TEMPTABLE STORAGE ENGINE,TMP_TABLE_SIZE,7.0,TMP_TABLE_SIZE defines the maximum size of internal in-memory temporary tables created by the TempTable storage engine
6,TEMPTABLE STORAGE ENGINE,MYSQL 8.0.28,7.0,The TempTable storage engine was introduced in MySQL 8.0.28
7,INNODB,INNODB_BUFFER_POOL_SIZE,9.0,INNODB_BUFFER_POOL_SIZE specifies the size of the buffer pool in InnoDB
8,INNODB,INNODB_MAX_DIRTY_PAGES_PCT_LWM,8.0,INNODB_MAX_DIRTY_PAGES_PCT_LWM defines a low water mark for dirty pages in InnoDB
9,INNODB,INNODB_PURGE_THREADS,8.0,INNODB_PURGE_THREADS specifies the number of background threads for the InnoDB purge operation
10,INNODB,INNODB_COMPRESSION_FAILURE_THRESHOLD_PCT,8.0,INNODB_COMPRESSION_FAILURE_THRESHOLD_PCT defines the compression failure rate threshold for a table in InnoDB
11,INNODB,INNODB_CHANGE_BUFFERING,8.0,INNODB_CHANGE_BUFFERING specifies whether InnoDB performs change buffering
12,INNODB,INNODB_ONLINE_ALTER_LOG_MAX_SIZE,1.0,INNODB_ONLINE_ALTER_LOG_MAX_SIZE specifies the upper limit on the size of temporary log files used during online DDL operations for InnoDB tables
13,INNODB,DDL OPERATION,8.0,"InnoDB supports online DDL operations, allowing changes to be made to the database schema while minimizing downtime and maintaining data integrity"
14,INNODB,DML OPERATION,7.0,"InnoDB allows concurrent DML operations during online DDL operations, enhancing database performance and availability"
15,INNODB,ALTER TABLE OPERATION,1.0,"InnoDB provides mechanisms to handle ALTER TABLE operations efficiently, ensuring that changes to table structures are applied with minimal disruption"
16,INNODB,INNODB_PURGE_BATCH_SIZE,7.0,"InnoDB uses the Purge Batch Size setting to manage the number of undo log pages processed in one batch, affecting the efficiency of the purge operation"
17,INNODB,INNODB_LRU_SCAN_DEPTH,7.0,"InnoDB utilizes the LRU Scan Depth parameter to control the flushing operation for the buffer pool, impacting performance and I/O capacity"
18,INNODB,INNODB_MAX_DIRTY_PAGES_PCT,7.0,"InnoDB uses the Max Dirty Pages Pct setting to guide the flushing activity, maintaining a balance between performance and data integrity"
19,INNODB,INNODB_WRITE_IO_THREADS,7.0,InnoDB configures the number of Write IO Threads to optimize the performance of write-intensive workloads
20,INNODB,INNODB_STATS_TRANSIENT_SAMPLE_PAGES,7.0,"InnoDB uses the Stats Transient Sample Pages parameter to determine the number of index pages sampled for statistics, affecting query execution plans"
21,INNODB,DIV_PRECISION_INCREMENT,6.0,InnoDB uses the Div Precision Increment variable to control the precision of numerical calculations in division operations
22,INNODB,INNODB_SPIN_WAIT_DELAY,6.0,"InnoDB uses the Spin Wait Delay parameter to manage the delay between polls for a spin lock, optimizing spin-lock polling delays"
23,INNODB,INNODB_COMPRESSION_PAD_PCT_MAX,6.0,"InnoDB uses the Compression Pad Pct Max setting to manage free space within compressed pages, allowing for data reorganization"
24,INNODB,INNODB_READ_AHEAD_THRESHOLD,7.0,"InnoDB uses the Read Ahead Threshold parameter to control linear read-ahead, optimizing page prefetching into the buffer pool"
25,INNODB,INNODB_CONCURRENCY_TICKETS,1.0,InnoDB uses the Concurrency Tickets setting to balance resource competition between small and large transactions
26,INNODB,MYSQL SERVER,16.0,InnoDB is a storage engine utilized by MySQL Server to manage data and provide advanced database features.
27,INNODB,FULLTEXT SEARCH INDEX,1.0,InnoDB supports full-text search indexing as part of its features
28,INNODB,FULLTEXT INDEX,7.0,InnoDB supports FullText Indexing for efficient text searching
29,INNODB,UNDO TABLESPACE,1.0,InnoDB uses Undo Tablespace to store rollback segments for transaction management
30,INNODB,THREADS,7.0,InnoDB uses Threads for parallel processing in FullText Indexing
31,QUERY_PREALLOC_SIZE,MYSQL 8.0.29,1.0,The query_prealloc_size variable was deprecated in MySQL 8.0.29
32,MYSQL SERVER,PERFORMANCE SCHEMA,7.0,Performance Schema is a feature of MySQL Server that helps in monitoring and performance tuning
33,MYSQL SERVER,MYISAM,6.0,MyISAM is a storage engine option available in MySQL Server
34,MYSQL SERVER,FULLTEXT SEARCH INDEX,7.0,MySQL Server supports full-text search indexing for efficient text data searching
35,MYSQL SERVER,HOST CACHE,7.0,Host cache is a feature of MySQL Server that optimizes client connection performance
36,MYSQL SERVER,BINLOG_ROW_IMAGE,6.0,Binlog_row_image is a MySQL Server variable that controls binary logging of row changes
37,MYSQL SERVER,TABLE_OPEN_CACHE,6.0,Table_open_cache is a MySQL Server variable that affects the number of open tables and file descriptors
38,MYSQL SERVER,INNODB_ADAPTIVE_MAX_SLEEP_DELAY,6.0,Innodb_adaptive_max_sleep_delay is a MySQL Server variable that dynamically adjusts thread sleep delay
39,MYSQL SERVER,INNODB_FT_TOTAL_CACHE_SIZE,6.0,Innodb_ft_total_cache_size is a MySQL Server variable that limits memory for full-text search indexes
40,MYSQL SERVER,READ_BUFFER_SIZE,6.0,Read_buffer_size is a MySQL Server variable that allocates buffers for sequential scans
41,MYSQL SERVER,EQ_RANGE_INDEX_DIVE_LIMIT,6.0,Eq_range_index_dive_limit is a MySQL Server variable that affects optimizer decisions for row estimates
42,MYSQL SERVER,INNODB_FLUSH_LOG_AT_TIMEOUT,6.0,Innodb_flush_log_at_timeout is a MySQL Server variable that controls log flushing frequency
43,MYSQL SERVER,KEY_CACHE_AGE_THRESHOLD,6.0,Key_cache_age_threshold is a MySQL Server variable that manages buffer demotion in the key cache
44,MYSQL SERVER,RANGE_ALLOC_BLOCK_SIZE,6.0,Range_alloc_block_size is a MySQL Server variable that defines block size for range optimization
45,MYSQL SERVER,INNODB_FT_SORT_PLL_DEGREE,1.0,Innodb_ft_sort_pll_degree is a MySQL Server variable that sets parallel indexing threads for full-text search
46,MYSQL SERVER,BINARY LOG,8.0,MySQL Server uses Binary Logs to record data modifications
47,MYSQL SERVER,ALLOCATION BLOCK SIZE,6.0,MySQL Server uses Allocation Block Size for optimizing range operations
48,MYSQL SERVER,TRANSACTION,1.0,MySQL Server manages Transactions to ensure data integrity
49,BINLOG_GROUP_COMMIT_SYNC_DELAY,BINLOG_GROUP_COMMIT_SYNC_NO_DELAY_COUNT,7.0,BINLOG_GROUP_COMMIT_SYNC_NO_DELAY_COUNT is dependent on the delay set by BINLOG_GROUP_COMMIT_SYNC_DELAY
50,INNODB_LOG_SPIN_CPU_ABS_LWM,INNODB_LOG_SPIN_CPU_PCT_HWM,1.0,Both variables define CPU usage thresholds for user threads spinning while waiting for flushed redo

## Entity extraction prompts

In [15]:
import json
from pathlib import Path

cache_dir = Path("/home/karimnazarovj/Rabbit/knowledge/postgres/graph/cache/entity_extraction")

def file_birth_time(path: Path):
    stat = path.stat()
    # On Linux, st_birthtime may not exist, so fall back to mtime.
    return getattr(stat, "st_birthtime", stat.st_mtime)

def extract_real_data_text(prompt_input: str) -> str:
    marker = "-Real Data-\n######################\nEntity_types:"
    start = prompt_input.find(marker)
    if start == -1:
        return ""

    text_marker = "\nText:"
    text_start = prompt_input.find(text_marker, start)
    if text_start == -1:
        return ""

    return prompt_input[text_start + len(text_marker):].strip()

rows = []

for path in sorted(cache_dir.iterdir(), key=file_birth_time):
    if not path.is_file():
        continue

    try:
        obj = json.loads(path.read_text())
    except Exception:
        continue

    rows.append({
        "file": path.name,
        "created": file_birth_time(path),
        "result": obj.get("result", "").strip(),
        "real_data_text": extract_real_data_text(obj.get("input", "")),
    })

# If you want the whole thing as a dataframe:
import pandas as pd
df = pd.DataFrame(rows)

# view
result = df[["file", "created", "real_data_text", "result"]]

# ToDo: Save this as a json array to output/entity_extraction_results.json 
result.to_json("/home/karimnazarovj/Rabbit/hallucination_discovery/output/entity_extraction_results.json", orient="records", indent=2)